import assert from "node:assert/strict";
import { JSDOM } from "jsdom";
import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { EffortSwitcher } from "../components/EffortSwitcher";
const dom = new JSDOM('<div id="root"></div>', { url: "http://localhost/", pretendToBeVisual: true });
Object.assign(globalThis, {window: dom.window, document: dom.window.document, HTMLElement: dom.window.HTMLElement, Node: dom.window.Node, IS_REACT_ACT_ENVIRONMENT: true});
dom.window.matchMedia = (() => ({matches:true, addEventListener(){},removeEventListener(){}})) as typeof window.matchMedia;
dom.window.requestAnimationFrame = (cb) => { cb(0); return 0; };
const rootEl = document.getElementById("root")!;
const root = createRoot(rootEl);
let selected = "";
await act(async () => root.render(<EffortSwitcher disabled={false} onPick={id => {selected=id;}} effort={{supported:true,current:"deliberate",default:"deliberate",levels:["auto","invalid-legacy-level"],options:[{id:"deliberate",name:"Deliberate"},{id:"brief",name:"Brief"}]}} />));
assert.match(rootEl.textContent!, /Deliberate/);
await act(async () => rootEl.querySelector("button")!.click());
const options = Array.from(document.querySelectorAll<HTMLButtonElement>('[role="option"]'));
assert.deepEqual(options.map(option=>option.textContent),["auto","Deliberate","Brief"]);
await act(async () => { options[2].click(); await new Promise(resolve=>setTimeout(resolve,5)); });
assert.equal(selected,"brief","UI submits adapter ID, not display label or global alias");
await act(async () => root.unmount());
console.log("PASS adapter-owned effort options and exact selection");
