import assert from "node:assert/strict";
import { useAppNavigationStore as store } from "../store/appNavigation";
store.getState().openPage({ kind: "automation" });
const link = store.getState().generation;
store.getState().openPage({ kind: "trash" });
store.getState().returnFromAutomationLink(link);
assert.equal(store.getState().page.kind, "trash", "late linked-session result cannot replace a newer page");
store.getState().openPage({ kind: "automation" });
store.getState().returnFromAutomationLink(store.getState().generation);
assert.equal(store.getState().page.kind, "workspace");
assert.equal(store.getState().automationReturn, true);
store.getState().enterConversation();
assert.equal(store.getState().automationReturn, false);
store.getState().setSettingsTarget("providers");
assert.deepEqual(store.getState().page, { kind: "settings", tab: "models" });
store.getState().returnToWorkspace();
assert.equal(store.getState().lastSettingsTarget, "models");
assert.equal(store.getState().visitedTrash, true);
assert.equal(store.getState().visitedAutomation, true);
console.log("PASS management navigation, legacy alias, page retention and linked-session generations");
