import assert from "node:assert/strict";
import { projectTranscriptTimeline, splitWindowedTimeline, defaultTranscriptRenderMode, type TimelineBlock } from "../lib/transcriptTimeline";
const blocks: TimelineBlock[] = Array.from({ length: 101 }, (_, index) => ({ key: `turn-${index}`, phase: "completed", rows: [], contentRevision: 1, measurementRevision: "1" }));
const active: TimelineBlock = { key: "active", phase: "active", rows: [], contentRevision: 2, measurementRevision: "2" };
const projection = projectTranscriptTimeline([...blocks, active], true);
assert.deepEqual(projection.completedBlocks, blocks);
assert.equal(projection.activeBlock, active);
assert.equal(projection.hasOlderHistory, true);
assert.equal(defaultTranscriptRenderMode(100), "full");
assert.equal(defaultTranscriptRenderMode(101), "windowed");
const split = splitWindowedTimeline(projection);
assert.deepEqual(split.cold, blocks.slice(0, 99));
assert.deepEqual(split.resident, blocks.slice(99));
const empty = projectTranscriptTimeline([], false);
assert.deepEqual(splitWindowedTimeline(empty), { cold: [], resident: [] });
assert.equal(empty.activeBlock, undefined);
assert.equal(empty.hasOlderHistory, false);
assert.equal(blocks.length, 101, "projection cannot mutate source history");
console.log("Timeline projection: completed/active isolation, paging, threshold and resident boundaries passed");
