import { registerHooks } from "node:module";
registerHooks({ resolve(specifier, context, nextResolve) { return specifier.endsWith(".svg") ? nextResolve("./asset-stub-for-tests.ts", { ...context, parentURL: import.meta.url }) : nextResolve(specifier, context); } });
import assert from "node:assert/strict";
import { managementDom } from "../test-support/managementDom";
import type { SessionMeta } from "../lib/types";
const dom = managementDom();
const { default: React, act } = await import("react");
const { createRoot } = await import("react-dom/client");
const { LocaleProvider } = await import("../lib/i18n");
const { TrashPage } = await import("../components/TrashPage");
const session = (id: string, recoveryCopy = false): SessionMeta => ({ path: id, title: id, preview: id, turns: 0, createdAt: 1, lastActivityAt: 1, modTime: 1, deletedAt: Date.now(), current: false, open: false, recoveryCopy });
let sessions = [session("a"), session("b"), session("protected", true)];
let latePreview!: () => void;
Object.assign(window, { go: { main: { App: { PreviewSession: (path: string) => path === "a" ? new Promise<never[]>((resolve) => { latePreview = () => resolve([]); }) : Promise.resolve([]) } } } });
const calls: string[] = [];
let listFails = false;
const list = async () => { if (listFails) throw new Error("read failure"); return sessions; };
const purge = async (path: string) => { calls.push(path); if (path === "b") throw new Error("busy"); sessions = sessions.filter((item) => item.path !== path); };
const restore = async (path: string) => { sessions = sessions.filter((item) => item.path !== path); listFails = true; };
const root = createRoot(document.getElementById("root")!);
const render = (active = true) => <LocaleProvider><TrashPage active={active} onBack={() => {}} list={list} purge={purge} restore={restore} /></LocaleProvider>;
const button = (text: string) => Array.from(document.querySelectorAll<HTMLButtonElement>("button")).find((node) => node.textContent?.trim() === text)!;
await act(async () => root.render(render()));
assert.equal(document.querySelector(".management-modal-backdrop"), null);
await act(async () => (document.querySelectorAll('.hist-item__main')[1] as HTMLButtonElement).click());
await act(async () => latePreview());
assert.equal(document.querySelector('.history-preview__title')?.textContent, "b", "late preview must not replace the selected conversation");
await act(async () => (document.querySelector('.history-clear') as HTMLButtonElement).click());
assert.ok(document.querySelector('[role="dialog"]')?.textContent?.includes("all 2 ordinary conversations"));
assert.equal(document.activeElement?.textContent, "Cancel", "destructive confirmation starts on cancel");
await act(async () => button("Confirm deletion").click());
assert.deepEqual(calls, ["a", "b"], "clear excludes recovery data and continues after failure");
assert.ok(document.body.textContent?.includes("Deleted 1; 1 did not complete."));
assert.equal(document.querySelector('.history-preview__title')?.textContent, "b");
await act(async () => button("Retry failed items").click());
assert.deepEqual(calls, ["a", "b", "b"], "explicit retry only targets failures");
await act(async () => button("Restore").click());
assert.ok(document.body.textContent?.includes("Operation completed, but the list could not refresh."));
assert.equal(document.querySelectorAll('.hist-item').length, 0, "successful restore is retained locally when refresh fails");
assert.ok(sessions.some((item) => item.path === "protected"));
await act(async () => root.render(render(false)));
assert.equal(document.querySelector('[role="dialog"]'), null);
await act(async () => root.unmount());
dom.window.close();
console.log("PASS trash page, stale preview, confirmation focus, recovery exclusion, failed-only retry and post-success refresh failure");
